### ISSUE TITLE
New Zealand: Scraper failing (Nil.attr)

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#25352]
https://morph.io/tmtmtmtm/new-zealand-parliament is currently failing with 
```
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:164:in `attr': undefined method `attribute' for nil:NilClass (NoMethodError)
 	from /app/lib/current_member_page.rb:25:in `block in <class:CurrentMemberPage>'
 	from /app/vendor/bundle/ruby/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:26:in `block in to_h'
 	from /app/vendor/bundle/ruby/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:25:in `map'
 	from /app/vendor/bundle/ruby/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:25:in `to_h'
 	from scraper.rb:31:in `block in <main>'
 	from scraper.rb:30:in `each'
 	from scraper.rb:30:in `<main>'
```

**Comment by ondenman** [comment]
@tmtmtmtm It looks like the scrape is running now.

**Comment by tmtmtmtm** [comment]
Not sure when this
