### ISSUE TITLE
Isle of Man: Broken scraper (Nil.tidy)

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#25365]
https://morph.io/tmtmtmtm/isle-of-man-house-of-keys is breaking with

```
scraper.rb:41:in `scrape_person': undefined method `tidy' for nil:NilClass (NoMethodError)
 	from scraper.rb:24:in `block in scrape_list'
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:23:in `scrape_list'
 	from scraper.rb:51:in `<main>'
```

**Comment by tmtmtmtm** [comment]
fixed by https://github.com/everypolitician-scrapers/isle-of-man-house-of-keys/commit/f26f5a317136b1480b96658a699c7e0fe0289ca0
