### ISSUE TITLE
Instructions in readme about Rakefiles don't work

### ISSUE THREAD

**Issue by henare** [everypolitician/everypolitician-data#737]
I followed the instructions in the readme about creating the two `Rakefile.rb`s but whenever I ran a rake command I got an error:

```
$ bundle exec rake clean
rake aborted!
NoMethodError: undefined method `instructions' for main:Object
/home/henare/Documents/projects/openaustralia/code/ukraine/everypolitician-data/rakefile_merged.rb:14:in `block in <top (required)>'
/home/henare/Documents/projects/openaustralia/code/ukraine/everypolitician-data/rakefile_merged.rb:3:in `<top (required)>'
/home/henare/Documents/projects/openaustralia/code/ukraine/everypolitician-data/data/Ukraine/Verkhovna_Rada/sources/Rakefile.rb:1:in `require_relative'
/home/henare/Documents/projects/openaustralia/code/ukraine/everypolitician-data/data/Ukraine/Verkhovna_Rada/sources/Rakefile.rb:1:in `<top (required)>'
/home/henare/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/home/henare/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
$
```

So I dug around the repo and ended up getting it working my copying Ireland. That just has a single `Rakefile.rb` in the root of the legislature that contains:

    require_relative '../../../rakefile_common.rb'

**Comment by tmtmtmtm** [comment]
Yeah — sorry about that. I pushed live a monster change yesterday morning that finally got rid of that process, but haven't had a chance to fix the docs yet https://github.com/everypolitician/everypolitician-data/pull/716
